apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml
- prometheus-operator/
- prometheus/
- alertmanager/
- grafana/

commonLabels:
  app.kubernetes.io/part-of: monitoring-stack