apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
  namespace: velero
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
  endpoints:
  - port: metrics
    interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: velero-alerts
  namespace: velero
  labels:
    release: prometheus-operator
spec:
  groups:
  - name: velero
    rules:
    - alert: VeleroBackupFailure
      expr: |
        velero_backup_failure_total > 0
      for: 1h
      labels:
        severity: critical
      annotations:
        summary: Velero backup failed
        description: Velero backup has failed. Check velero logs for more details.

    - alert: VeleroBackupPartialFailure
      expr: |
        velero_backup_partial_failure_total > 0
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: Velero backup partially failed
        description: Some items in Velero backup have failed. Check velero logs.

    - alert: NoRecentBackup
      expr: |
        time() - max(velero_backup_last_successful_timestamp) > 86400
      labels:
        severity: warning
      annotations:
        summary: No recent successful backup
        description: No successful Velero backup in the last 24 hours.