apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-cluster-backup
  namespace: velero
spec:
  schedule: "0 0 * * *"  # Daily at midnight
  template:
    includedNamespaces:
      - monitoring
      - gatekeeper-system
      - litmus
      - argocd
    excludedResources:
      - nodes
      - events
      - events.events.k8s.io
    includeClusterResources: true
    storageLocation: aws-backup
    volumeSnapshotLocations:
      - aws-snapshots
    ttl: 720h  # 30 days

---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: aws-backup
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: eks-platform-backup
    prefix: prod
  config:
    region: ap-south-1

---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: aws-snapshots
  namespace: velero
spec:
  provider: aws
  config:
    region: ap-south-1