apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-exporter
  namespace: litmus
spec:
  selector:
    matchLabels:
      app: chaos-exporter
  template:
    metadata:
      labels:
        app: chaos-exporter
    spec:
      containers:
      - name: chaos-exporter
        image: litmuschaos/chaos-exporter:latest
        ports:
        - containerPort: 8080
        env:
        - name: WATCH_NAMESPACE
          value: litmus
        - name: PROMETHEUS_PORT
          value: "8080"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: chaos-exporter
  namespace: litmus
  labels:
    app: chaos-exporter
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: metrics
  selector:
    app: chaos-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chaos-exporter
  namespace: litmus
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: chaos-exporter
  endpoints:
  - port: metrics