apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

bases:
  - ../../base

patchesStrategicMerge:
  - gatekeeper-values.yaml

configMapGenerator:
  - name: prod-policy-config
    files:
      - policies/strict-pod-security.yaml
      - policies/prod-network-policies.yaml