apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  test.conf: |
    key1=value1
    key2=value2

---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
stringData:
  username: test-user
  password: test-password