apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-service-monitor
spec:
  selector:
    matchLabels:
      app: test-app
  endpoints:
  - port: metrics

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-prometheus-rule
spec:
  groups:
  - name: test.rules
    rules:
    - alert: TestAlert
      expr: vector(1)
      labels:
        severity: warning
      annotations:
        summary: "Test alert"