apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

bases:
  - ../../base

patchesStrategicMerge:
  - prometheus-values.yaml
  - grafana-values.yaml

configMapGenerator:
  - name: alertmanager-config
    files:
      - alertmanager.yaml