apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-maintenance-windows
  namespace: argocd
data:
  prod-maintenance: |
    schedule: "0 1 * * 0"  # Sunday 1 AM
    duration: 4h
    applications:
      - monitoring-prod
      - policies-prod
      - chaos-prod
    operations:
      - sync
      - refresh
      - prune
    notify:
      - slack-maintenance
      - pagerduty-maintenance

  staging-maintenance: |
    schedule: "0 1 * * 3"  # Wednesday 1 AM
    duration: 4h
    applications:
      - monitoring-staging
      - policies-staging
      - chaos-staging
    operations:
      - sync
      - refresh
      - prune
    notify:
      - slack-maintenance

  dev-maintenance: |
    schedule: "0 1 * * *"  # Daily 1 AM
    duration: 2h
    applications:
      - monitoring-dev
      - policies-dev
      - chaos-dev
    operations:
      - sync
      - refresh
      - prune
    notify:
      - slack-maintenance