apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litmus

resources:
- namespace.yaml
- operator.yaml
- experiments/

commonLabels:
  app.kubernetes.io/part-of: chaos-engineering