blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/OWNER/REPO/security/policy
    about: Please report security vulnerabilities according to our security policy
  - name: Question or Discussion
    url: https://github.com/OWNER/REPO/discussions
    about: Ask questions and discuss with other community members