apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litmus

bases:
  - ../../base

patchesStrategicMerge:
  - chaos-values.yaml

configMapGenerator:
  - name: prod-chaos-config
    files:
      - schedules/prod-schedule.yaml
      - workflows/prod-workflow.yaml