apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gatekeeper
      version: ">=3.9.0"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: gatekeeper-system
  values:
    replicas: 3
    auditInterval: 300
    constraintViolationsLimit: 20
    audit:
      enabled: true
      logLevel: INFO
    controllerManager:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    image:
      pullPolicy: IfNotPresent
    podAnnotations:
      co.elastic.logs/enabled: "true"