apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system

resources:
- namespace.yaml
- gatekeeper.yaml
- constraints/
- templates/

commonLabels:
  app.kubernetes.io/part-of: policy-control